language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
install:
  - pip install AWSIoTPythonSDK
  - pip install boto3
  - pip install fake_rpi
  - pip install awscli
before-script:
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY
  - aws configure set aws_secret_access_key $AWS_SECRET_KEY
  - aws configure set region $AWS_REGION
script:
  - pytest Source/test.py
